### ISSUE TITLE
Visual indication of current file being edited

### ISSUE THREAD

**Issue by sogaiu** [Saikyun/freja#13]
Perhaps it's worth having some visual indication of the name (of file path?) of the current file being edited (if there is a related file).

**Comment by Saikyun** [comment]
Good idea. :) I wonder what would look the best. I guess one could start with just changing the title (since currently you can only look at one file at the time). It wouldn't eat vertical space either. :)

**Comment by sogaiu** [comment]
May be as long as the target is "desktop", the following from raylib can work?
```
void SetWindowTitle(const char *title);
```

**Comment by Saikyun** [comment]
Fixed with:
f5978cef08c31ee3613592df73ce3a68ec3291b3
d4038aab91ff3f78f3a2b278a21a6b792480b53d

**Comment by sogaiu** [comment]
Yay!  It is working here :)
