### ISSUE TITLE
Design layouting system

### ISSUE THREAD

**Issue by saikyun** [saikyun/freja#17]
When creating GUI components (e.g. menus), it is desirable to make it easy to do certain things:
- absolute positioning
- relative positioning (left, center, right aligned)
- "float" things next to each other
- grids

Currently this is not possible. Would be nice to gather more things that would be nice to do wrt layouting here.

**Comment by Saikyun** [comment]
Sizes are implemented. Need to add positions too. Then use all that information when rendering / receiving events.

**Comment by Saikyun** [comment]
Some initial work has been done: https://github.com/Saikyun/freja-layouting
Need to start using it inside freja. Will start with menu.

**Comment by saikyun** [comment]
Now the menu is added. Seems to work so far.
