### ISSUE TITLE
Behavior when search fails and/or reaches the end of source

### ISSUE THREAD

**Issue by sogaiu** [saikyun/freja#2]
May be if a search fails there could be some kind of feedback.

Also, if a search has "reached the end of source", perhaps similar feedback could be given and/or the search could wrap.

Just some ideas.

**Comment by saikyun** [comment]
With commit the search does wrap: https://github.com/saikyun/freja/commit/e89face5c0a4cc0f1e5b6aa5f73a8f058824cc16 

Need to consider failed search. Maybe the search bar could just show nof matches and which one you're currently on.

**Comment by sogaiu** [comment]
Seems to be working :+1:

**Comment by saikyun** [comment]
Now it shows which match you're at with: https://github.com/saikyun/freja/commit/2d02c05651a061af38acfa0378eb49cebd95d67f

**Comment by saikyun** [comment]
Accidentally pushed buggy code, should be fixed in: https://github.com/saikyun/freja/commit/50efbc4080125b4effee17ef55f37dc538ae80ae
