### ISSUE TITLE
Be able to identify freja version from the binary

### ISSUE THREAD

**Issue by saikyun** [saikyun/freja#20]
E.g. display specific commit used when building.

**Comment by saikyun** [comment]
Do you know how to get code from running a bash script into a Janet
program? I don't really want to force Freja to be dependent on eg git to
get the commit. Maybe it could be fed as a environment variable when
running or building. Is this something that could be done in project.janet?

Den tis 31 aug. 2021 14:20sogaiu ***@***.***> skrev:

**Comment by andrewchambers** [comment]
I would just load it into a global def - (def version (or (os/run ...) nil))

**Comment by saikyun** [comment]
But what if a user running a pre-built binary doesn't have git? (latest git
commit is what I figure I'd use as part of the version)

Den tis 31 aug. 2021 kl 16:41 skrev andrewchambers ***@***.***

**Comment by saikyun** [comment]
Assuming you mean os/spawn, since it throws error when you don't have the
program :(

Preferably I'd only set the version when running from source or building,
in the built binary I'd want it to be static.

Den tis 31 aug. 2021 kl 17:22 skrev Jona Ekenberg ***@***.***>:

**Comment by andrewchambers** [comment]
defs are run at compile time not runtime...

**Comment by saikyun** [comment]
Oh, right, haha. Thanks!

Den tis 31 aug. 2021 17:27andrewchambers ***@***.***> skrev:

**Comment by saikyun** [comment]
Fixed with #32 , thanks again @sogaiu :) And thanks @andrewchambers for the input.
