### ISSUE TITLE
Command line option(s) to open a file to a specific location

### ISSUE THREAD

**Issue by sogaiu** [saikyun/freja#28]
It would be nice to be able to get freja to open a file and have the cursor (and the area that one is viewing) be at a particular line (and possibly column).

One important use case of this type of feature is for other programs to make use of it.

**Comment by saikyun** [comment]
If you start freja like this: `freja file.x:123:5` it will go to line 123 and column 5. Please try it. :)

**Comment by sogaiu** [comment]
It seems to be working!

Thank you :)
