### ISSUE TITLE
Prerequisites review reminder wrt jpm

### ISSUE THREAD

**Issue by sogaiu** [saikyun/freja#30]
jpm doesn't currently come with a git clone of janet's repository.

As far as I know, it's not quite clear how folks are going to be expected to install it yet.

This issue is just a reminder to revisit the prerequisites section of the README if separate installation of jpm becomes the norm.

**Comment by sogaiu** [comment]
[Janet's Makefile acquired a new target named `install-jpm-git`](https://github.com/janet-lang/janet/commit/31a7fdc7b6faef304bc924c7a2c43320aea701e2).  If one is building and installing Janet from the source repository, this can be used to install jpm.

One thing worth noting might be that if one uses `PREFIX` while building janet, it's likely important to use that for the `install-jpm-target` as well.

Recently I've been using:
```
make clean && \
PREFIX=$HOME/.local make && \
PREFIX=$HOME/.local make install
```
to intall janet, so for jpm installation I would do:
```
PREFIX=$HOME/.local make install-jpm.git
```

One reason to use `PREFIX` like this is that it makes it straight-forward to test multiple versions of janet using multiple user accounts.

Suppose I want to test version A and version B of janet.

I can install version A of janet for user X and test there.

I can also install version B of janet for user Y and test there separarely.

So at least for people who need to investigate issues related to versions, it's much nicer to be able to have multiple installations of something within a single OS -- and currently, a relatively cheap and straight-forward way to do this is with multiple accounts if the software in question can be made to function installed in a variety of locations.

One can also use virtual machines (like VirtualBox), Docker, or NixOS / guix for this sort of thing.  They all have their various trade-offs.

**Comment by saikyun** [comment]
For now I added a note that the user has to install jpm. I've removed notes about prefix for now, those were mostly for when I was replacing regular jaylib. Now freja-jaylib is a separate package. I'll link to this issue if someone wants to do it with prefixes, thanks for the details. :)
