### ISSUE TITLE
Absolute coordinates affect the "code part" of the screen

### ISSUE THREAD

**Issue by greenfork** [saikyun/freja#45]
I'm not really sure what's wrong here. Probably mouse position is not captured properly?

https://user-images.githubusercontent.com/20167110/137634340-56c672b1-8a9d-4616-b6fe-1e1e8936e66a.mp4

This is an adapted example from the jaylib repo:

```janet
#(import freja-jaylib :as jl)
(import freja/flow :as jl)

#(defn init []
#  (jl/init-window 800 600 "Test Game")
#  (jl/set-target-fps 60)
#  (jl/hide-cursor))

#(defn deinit []
#  (jl/close-window))

(defn render [el]
  (when (el :focused?)
    (def {:width w :height h} el)
    (jl/begin-drawing)

    (jl/clear-background [0 0 0])
    (let [[x y] (jl/get-mouse-position)]
      (jl/draw-circle-gradient x y 31.4 :lime :red)
      (jl/draw-poly [200 100] 5 40 0 :magenta)
      (jl/draw-line-bezier
        [(- x 100) y]
        [(+ x 100) (+ y 50)]
        4 :pink)
      (jl/draw-line-ex
        [x (- y 10)]
        [x (+ y 10)]
        4 :sky-blue)
      (jl/draw-line-strip
        [[x 0] [x 100] [50 y] [10 180]]
        :ray-white))
    (jl/end-drawing)))

#(defn main-loop []
#  (while (not (jl/window-should-close))
#    (render 1)))

(jl/start-game {:render render})

#(defn main [& args]
#  (init)
#  (main-loop)
#  (deinit))
```

**Comment by saikyun** [comment]
Okay, so multiple things happening here:

1. You don't need begin-drawing / end-drawing when running in freja, freja runs those :) This is what causes the flickering. Put them in the main-loop-function.
2. you don't need clear-background. If you want a background, you'll have to use draw-rectangle
3.  `get-mouse-position` returns the "global position". To get the relative position, you can do this:
```
    (def {:width w :height h :render-x rx :render-y ry} el)
    # ...
        (let [[x y] (jl/get-mouse-position)
               x (- x rx)
               y (- y ry)]
```

**Comment by greenfork** [comment]
I'm not totally sure about the mouse position but the basic problems with flickering are solved, thanks a lot!

**Comment by saikyun** [comment]
Hmm, okay, you can verify that you're getting the local mouse position by
eg rendering a circle using the calculated x and y. :)

Den mån 18 okt. 2021 15:31Dmitry Matveyev ***@***.***> skrev:

**Comment by greenfork** [comment]
Basically yes, I have a "cursor" for my game, so this works for me :D

**Comment by saikyun** [comment]
Okay, nice. :)
