### ISSUE TITLE
Behavior for quitting

### ISSUE THREAD

**Issue by sogaiu** [saikyun/freja#5]
May be it would be nice to confirm quitting if there are unsaved changes?

**Comment by Saikyun** [comment]
I wonder what approach might make most sense. Perhaps a good old popup is fine.

**Comment by sogaiu** [comment]
If that's the simplest thing to do and nothing else comes about, may be it's good enough?

Perhaps It's the kind of thing that could be replaced later without significant consequences.

**Comment by Saikyun** [comment]
Yeah, it would be a pretty surface level thing. :)

**Comment by saikyun** [comment]
So far new checkpoint system seems to be working well. https://github.com/saikyun/freja-checkpoints
Main missing part is behaviour when starting freja without a file as input, and that opening files seem to act strange atm. Will keep working on those issues.

**Comment by saikyun** [comment]
Now a scratch file is created and opened when starting freja. Will need to test freja-checkpoints on windows too though, since now linux setup is assumed.

Need to fix opening files, then it should be done for linux.

**Comment by saikyun** [comment]
Oh, and I need to store a checkpoint when opening a file too. Right now it's possible to open a file with no checkpoints, make changes, and be unable to go back.

**Comment by saikyun** [comment]
Fixed the above. Now I just need to move this stuff into regular freja instead of relying on user to include in init.janet.

**Comment by saikyun** [comment]
Now added to freja properly.
