### ISSUE TITLE
current match behaviour in janet causes freja to blank screen

### ISSUE THREAD

**Issue by saikyun** [saikyun/freja#56]
related issue: https://github.com/janet-lang/janet/issues/863

hotfix: use janet commit 7205ee5e0a15d7508e981b74584d096612155481

**Comment by saikyun** [comment]
Fixed with 173f21917c9c26f2adcb2d4b0fc4e792c1c663d5

**Comment by sogaiu** [comment]
Thank you!

Really appreciate it :)
