### ISSUE TITLE
gb/column! seems to report incorrect value sometimes

### ISSUE THREAD

**Issue by sogaiu** [saikyun/freja#60]
With freja at commit: 700137587b450ae504c5f981a991be9e3fc3ee30 and the following as the editor buffer content:
```
(import freja/new_gap_buffer :as gb)
(import freja/state)
(import freja/default-hotkeys :as dh)
    
(defn current-gb
  []
  (get-in state/editor-state [:stack 0 1 :editor :gb]))
```
and the cursor at the end of the first line, evaluating:
```
(gb/column! (current-gb) ((current-gb) :caret))
```
via `eval-expr-dialog` (default hotkey ctrl-shift-e), yields `0` here.

The value I expected was non-zero, or the column number corresponding to the last cursor position(?) of the first line.  I think that should be `36` in this case.

With the cursor at the end of some other lines (e.g. the second or third line) I get values that appear to make sense.  `20` for the second line and `37` for the third line.

**Comment by sogaiu** [comment]
This is a guess, but may be this occurs because `column!` indirectly relies on a peg which might require that there is an end of line indicator: https://github.com/saikyun/freja/blob/700137587b450ae504c5f981a991be9e3fc3ee30/freja/new_gap_buffer.janet#L1268

The case that reproduces above is the first line and the position of the cursor is before all newlines in the buffer.

**Comment by sogaiu** [comment]
Perhaps if `peg/match` fails here: https://github.com/saikyun/freja/blob/700137587b450ae504c5f981a991be9e3fc3ee30/freja/new_gap_buffer.janet#L1277 a little bit more processing could happen here: https://github.com/saikyun/freja/blob/700137587b450ae504c5f981a991be9e3fc3ee30/freja/new_gap_buffer.janet#L1279 before settling on a final number.

**Comment by saikyun** [comment]
Should be fixed with a1661157eca47c2bdae3ba199a83a15ac1c856c1
Please try it :)

**Comment by sogaiu** [comment]
Seems to be working better :)

TYVM!

**Comment by saikyun** [comment]
Nice :D

Den tis 15 feb. 2022 14:02sogaiu ***@***.***> skrev:
