### ISSUE TITLE
Compile error: undefined symbold: GetDroppedFiles

### ISSUE THREAD

**Issue by tionis** [saikyun/freja#64]
I'm getting a compile error when building the project:
```
generating executable c source build/freja.c from /home/tionis/freja/freja/main.janet...
error: could not load native /home/tionis/.local/lib/janet/freja-jaylib.so: /home/tionis/.local/lib/janet/freja-jaylib.so: undefined symbol: GetDroppedFiles
```
I'm using the current master of both janet and jpm in an install with `PREFIX=$HOME/.local` setup so that all deps should install into ~/.local/lib/janet/...

**Comment by sogaiu** [comment]
I get a similar, but not quite the same error:

```
generating executable c source build/freja.c from /tmp/freja/freja/main.janet...
error: could not load native /home/user/.local/lib/janet/freja-jaylib.so: /home/user/.local/lib/janet/freja-jaylib.so: undefined symbol: DrawTextureQuad
```

I have a similar janet / jpm setup.

**Comment by sogaiu** [comment]
When I try with the `new-freja-jaylib` branch though, compilation succeeds.

**Comment by saikyun** [comment]
Hey tionis, sorry for the late reply, for some reason I didn't get an email for this. Gonna double check my notification settings.

I've sort of worked under the assumption that no one uses freja, and have therefore been terribly lax with making sure things build correctly. I apologize for this. I can't promise any time that I'll fix it, but I am happy to help if you have any other issues.

If you want to contact me more directly, we have a freja-discord that I check daily. :) Have a nice day!

**Comment by tionis** [comment]
No worries, I was just trying it out to maybe write some janet in it, so not using it in any serious capacity.

**Comment by sogaiu** [comment]
@tionis Building the `main` branch (068deb7a3ac1ce405443ebf889b9ed0a643c28e0) works for me ATM.

May be it's ok to close?

**Comment by tionis** [comment]
Yes, you're right, it seems to be fixed!
It's compiling fine for me without any problems, I'll close this then.
Thanks for the ping.
